# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Updates for Github Actions used in the repo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "element-hq/element-android-reviewers"
    ignore:
      - dependency-name: "*"
  # Updates for Gradle dependencies used in the app
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 200
    reviewers:
      - "element-hq/element-android-reviewers"
    allow:
      - dependency-name: "io.element.android:wysiwyg"
      - dependency-name: "org.matrix.rustcomponents:crypto-android"
