/*
 * Copyright 2025 New Vector Ltd.
 * Copyright 2020 The Matrix.org Foundation C.I.C.
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
 * Please see LICENSE files in the repository root for full details.
 */
package org.matrix.android.sdk.internal.session.identity.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
internal data class IdentityRequestOwnershipParams(
        /**
         * Required. The client secret that was supplied to the requestToken call.
         */
        @Json(name = "client_secret")
        val clientSecret: String,

        /**
         * Required. The session ID, generated by the requestToken call.
         */
        @Json(name = "sid")
        val sid: String,

        /**
         * Required. The token generated by the requestToken call and sent to the user.
         */
        @Json(name = "token")
        val token: String
)
