/*
 * Copyright 2025 New Vector Ltd.
 * Copyright 2020 The Matrix.org Foundation C.I.C.
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
 * Please see LICENSE files in the repository root for full details.
 */

package org.matrix.android.sdk.api.session.events.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class UnsignedData(
        /**
         * The time in milliseconds that has elapsed since the event was sent.
         * This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers
         * is out of sync, which can cause the age to either be negative or greater than it actually is.
         */
        @Json(name = "age") val age: Long?,
        /**
         *  Optional. The event that redacted this event, if any.
         */
        @Json(name = "redacted_because") val redactedEvent: Event? = null,
        /**
         * The client-supplied transaction ID, if the client being given the event is the same one which sent it.
         */
        @Json(name = "transaction_id") val transactionId: String? = null,
        /**
         * Optional. The previous content for this event. If there is no previous content, this key will be missing.
         */
        @Json(name = "prev_content") val prevContent: Map<String, Any>? = null,
        @Json(name = "m.relations") val relations: AggregatedRelations? = null,
        /**
         * Optional. The eventId of the previous state event being replaced.
         */
        @Json(name = "replaces_state") val replacesState: String? = null

)

fun UnsignedData?.isRedacted() = this?.redactedEvent != null
