name: Move P1 bugs to boards

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  p1_issues_to_team_workboard:
    runs-on: ubuntu-latest
    # Skip in forks
    if: >
      github.repository == 'vector-im/element-android' &&
      (!contains(github.event.issue.labels.*.name, 'A-E2EE') &&
        !contains(github.event.issue.labels.*.name, 'A-E2EE-Cross-Signing') &&
        !contains(github.event.issue.labels.*.name, 'A-E2EE-Dehydration') &&
        !contains(github.event.issue.labels.*.name, 'A-E2EE-Key-Backup') &&
        !contains(github.event.issue.labels.*.name, 'A-E2EE-SAS-Verification')) &&
      (contains(github.event.issue.labels.*.name, 'T-Defect') &&
        contains(github.event.issue.labels.*.name, 'S-Critical') &&
        (contains(github.event.issue.labels.*.name, 'O-Frequent') ||
          contains(github.event.issue.labels.*.name, 'O-Occasional')) ||
        contains(github.event.issue.labels.*.name, 'S-Major') &&
        contains(github.event.issue.labels.*.name, 'O-Frequent') ||
        contains(github.event.issue.labels.*.name, 'A11y') &&
        contains(github.event.issue.labels.*.name, 'O-Frequent'))
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Android App Team
          column: Important Issues & Topics (P1)
          repo-token: ${{ secrets.ELEMENT_BOT_TOKEN }}

  P1_issues_to_crypto_team_workboard:
    runs-on: ubuntu-latest
    # Skip in forks
    if: >
      github.repository == 'vector-im/element-android' &&
      (contains(github.event.issue.labels.*.name, 'Z-UISI') ||
        (contains(github.event.issue.labels.*.name, 'A-E2EE') ||
        contains(github.event.issue.labels.*.name, 'A-E2EE-Cross-Signing') ||
        contains(github.event.issue.labels.*.name, 'A-E2EE-Dehydration') ||
        contains(github.event.issue.labels.*.name, 'A-E2EE-Key-Backup') ||
        contains(github.event.issue.labels.*.name, 'A-E2EE-SAS-Verification')) &&
      (contains(github.event.issue.labels.*.name, 'T-Defect') &&
        contains(github.event.issue.labels.*.name, 'S-Critical') &&
        (contains(github.event.issue.labels.*.name, 'O-Frequent') ||
          contains(github.event.issue.labels.*.name, 'O-Occasional')) ||
        contains(github.event.issue.labels.*.name, 'S-Major') &&
        contains(github.event.issue.labels.*.name, 'O-Frequent') ||
        contains(github.event.issue.labels.*.name, 'A11y') &&
        contains(github.event.issue.labels.*.name, 'O-Frequent')))
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Crypto Team
          column: Ready
          repo-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
